name: Readme Update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Check directory content before setup
        run: |
          pwd
          ls -la
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: | 
          npm ci
          npm list rss-parser
      
      - name: Update README
        run: |
          node index.js
          ls -la
          cat README.md || echo "README.md not found"
      
      - name: Configure Git
        run: |
          git config --local user.email "juyeonbae.dev@gmail.com"
          git config --local user.name "juyeonbae"
      
      - name: Check Git Status
        run: |
          git status
          git diff
      
      - name: Commit and Push
        run: |
          git add README.md
          git commit -m "Update README.md" || echo "No changes to commit"
          git push origin main || echo "No changes to push"