name: Update README and Fetch Blog Posts

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 리포지토리 체크아웃
      - uses: actions/checkout@v3

      # Node.js 설정
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # 종속성 설치
      - name: Install dependencies
        run: npm ci

      # README 업데이트 및 블로그 포스팅 가져오기
      - name: Run scripts
        run: npm start

      # 변경 사항 커밋 및 푸시
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 이건 안 만들었음
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git add .
          git config --local user.email "ilnyu0756@naver.com"
          git config --local user.name "juyeonbae"
          git commit -m "Update README and Fetch Blog Posts"
          git push https://juyeonbae:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/juyeonbae/Blog.git